language: node_js
sudo: required
services:
        - docker
before_install:
        - docker build -t mohgamalmoh/docker-react -f Dockerfile.dev .
           
script:
        - docker run -e CI=true mohgamalmoh/docker-react npm run test

deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "docker"
        env: "Docker-env"
        bucket_name: "elasticbeanstalk-us-east-2-722072946654"
        bucket_path: "docker"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "$AWS_SECRET_ACCESS_KEY"
