language: node_js
sudo: required
deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "docker"
        env: "Docker-env"
        bucket_name: "elasticbeanstalk-us-east-2-722072946654"
        bucket_path: "docker"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "$AWS_SECRET_ACCESS_KEY"
