sudo: required
services:
        - docker
before_install:
        - docker build -t mohgamalmoh/docker-react -f Dockerfile.dev .
           
script:
        - docker run mohgamalmoh/docker-react npm run test -- --coverage
