version: '3'
services:
        web:
                build:
                        context: . 
                        dockerfile: Dockerfile
                ports:
                        - "80:3000"
                volumes:
                        - /app/node_modules
                        - .:/app
